# Generated by Django 5.2.3 on 2025-07-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('nid_no', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('employment_type', models.CharField(blank=True, choices=[('general_regular', 'General(Regular)'), ('general_probation', 'General(Probation)'), ('teacher_regular', 'Teacher(Regular)'), ('teacher_probation', 'Teacher(Probation)')], default='general_probation', max_length=20, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('probation_period', models.IntegerField(blank=True, default=3, help_text='Probation period in months', null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('office_days', models.CharField(blank=True, default='Monday-Friday', max_length=100)),
                ('office_time', models.CharField(blank=True, default='09:00-18:00', help_text='Format: HH:MM-HH:MM', max_length=100, null=True)),
                ('office_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rfid_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('present_address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Present address')),
                ('permanent_address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Permanent address')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('religion', models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('buddhist', 'Buddhist'), ('jain', 'Jain'), ('other', 'Other')], max_length=50, null=True, verbose_name='Religion')),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='Blood Group')),
                ('gender', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('personal_mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Personal Mobile Number')),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Personal Email ID')),
                ('last_education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Education')),
                ('educational_institute', models.CharField(blank=True, max_length=100, null=True, verbose_name='Educational Institute')),
                ('last_job_experience', models.TextField(blank=True, null=True, verbose_name='Last job experience')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics/', verbose_name='Profile Picture upload')),
                ('system_access', models.TextField(blank=True, choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('guest', 'Guest')], null=True, verbose_name='System Access (E application)')),
                ('security_clearance', models.CharField(blank=True, max_length=20, verbose_name='Security Clearance Level (E application)')),
                ('shift_preference', models.CharField(blank=True, max_length=100, verbose_name='Self-Monitoring (default or pre-experienced units)')),
                ('bank_details', models.TextField(blank=True)),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='Resigned / Terminated Date')),
                ('resign_reason', models.TextField(blank=True, verbose_name='Resigned / Terminated Reason')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.designation')),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_name', to='users.user')),
            ],
        ),
    ]
