# Generated by Django 5.2.3 on 2025-07-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.leavegroup'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_by', to='leave_management.supervisor'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nominee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.nominee'),
        ),
    ]
