# Generated by Django 5.2.3 on 2025-07-21 18:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveGroup',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('start_day', models.PositiveSmallIntegerField(default=1)),
                ('end_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12)),
                ('end_day', models.PositiveSmallIntegerField(default=31)),
                ('is_active', models.BooleanField(default=True, help_text='If checked, this reset period is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Reset Period',
                'verbose_name_plural': 'Leave Reset Periods',
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('medical', 'Medical Leave'), ('casual', 'Casual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('annual', 'Annual Leave'), ('compensatory', 'Compensatory Leave'), ('duty', 'Duty Leave / On-Duty'), ('bereavement', 'Bereavement Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave')], max_length=50, verbose_name='Leave Type')),
                ('gender', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('apply_before_days', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.CharField(blank=True, choices=[('joining', 'From Joining'), ('confirmation', 'After Confirmation'), ('one_year', 'After 1 Year Service')], max_length=20, null=True)),
                ('total_leave_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('max_days_per_request', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('min_days_per_request', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('allow_half_day', models.BooleanField(blank=True, default=False, null=True)),
                ('count_holidays', models.BooleanField(blank=True, default=False, null=True)),
                ('count_weekends', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('validity', models.PositiveIntegerField(blank=True, default=0, help_text='Validity in days for the leave policy', null=True)),
                ('leave_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavegroup')),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending_L1', 'Pending Level 1'), ('pending_L2', 'Pending Level 2'), ('pending_L3', 'Pending Level 3'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_L1', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('days_count', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_half_day', models.BooleanField(blank=True, default=False, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employee.employee')),
                ('leave_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavepolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_employees', to='employee.employee')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors_of', to='employee.employee')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('employee', 'supervisor', 'level')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True)),
                ('level', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('leave_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavepolicy')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.leaverequest')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_transferred', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('year', models.DateField(blank=True, help_text='Year when the transfer occurred. Defaults to current year.', null=True)),
                ('transfer_identifier', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_transfers', to='employee.employee')),
                ('from_leave_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='leave_management.leavegroup')),
                ('from_leave_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='leave_management.leavepolicy')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.leavetransfer')),
                ('to_leave_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='leave_management.leavegroup')),
                ('to_leave_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='leave_management.leavepolicy')),
            ],
            options={
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['employee', 'year'], name='leave_manag_employe_160e9f_idx'), models.Index(fields=['transfer_identifier'], name='leave_manag_transfe_9f7640_idx')],
            },
        ),
    ]
