# Generated by Django 5.2.1 on 2025-07-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetransfer',
            name='transfer_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leavetransfer',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year when the transfer occurred.', null=True),
        ),
    ]
