# Generated by Django 5.2.1 on 2025-07-22 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_alter_leavetransfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetransfer',
            name='transfer_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leavetransfer',
            name='transfer_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='leavetransfer',
            name='year',
            field=models.DateField(blank=True, help_text='Year when the transfer occurred. Defaults to current year.', null=True),
        ),
    ]
