# Generated by Django 5.2.1 on 2025-07-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leavetransfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedLeaveTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_types', models.CharField(blank=True, choices=[('medical', 'Medical Leave'), ('casual', 'Casual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('annual', 'Annual Leave'), ('compensatory', 'Compensatory Leave'), ('duty', 'Duty Leave / On-Duty'), ('bereavement', 'Bereavement Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave')], max_length=50, null=True)),
            ],
        ),
    ]
