# Generated by Django 5.2.1 on 2025-07-28 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_allowedleavetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedleavetypes',
            name='leave_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavepolicy'),
        ),
        migrations.RemoveField(
            model_name='allowedleavetypes',
            name='allowed_types',
        ),
        migrations.AddField(
            model_name='allowedleavetypes',
            name='allowed_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_types', to='leave_management.leavepolicy'),
        ),
    ]
