# Generated by Django 5.2.1 on 2025-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_allowedleavetypes_leave_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutOffDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_off_day', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
