# Generated by Django 5.2.1 on 2025-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_cutoffdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('days_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_holiday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
