# Generated by Django 5.2.1 on 2025-08-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        ('leave_management', '0007_holiday_leaverequest_is_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_no', models.CharField(blank=True, max_length=20, null=True)),
                ('attendance_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('half_day', 'Half Day'), ('late_in', 'Late In'), ('early_out', 'Early Out')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employee.employee')),
            ],
            options={
                'ordering': ['-attendance_date'],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(blank=True, choices=[('forgot_sign_in', 'Forgot Sign In'), ('forgot_sign_out', 'Forgot Sign Out'), ('traffic_delay', 'Traffic Delay'), ('personal_emergency', 'Personal Emergency')], max_length=50, null=True)),
                ('timeframe_start', models.DateTimeField(blank=True, null=True)),
                ('timeframe_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_adjustments', to='attendence.attendance')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_adjustments', to='employee.employee')),
            ],
            options={
                'ordering': ['-timeframe_start'],
                'unique_together': {('employee', 'attendance', 'adjustment_type')},
            },
        ),
        migrations.CreateModel(
            name='AdjustmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_approvals', to='leave_management.supervisor')),
                ('adjustment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_approvals', to='attendence.attendanceadjustment')),
            ],
        ),
    ]
