# Generated by Django 5.2.1 on 2025-08-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_alter_attendanceadjustment_timeframe_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='timeframe_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
