# Generated by Django 5.2.1 on 2025-08-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_alter_attendanceadjustment_timeframe_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='status',
            field=models.CharField(choices=[('pending_L1', 'Pending Level 1'), ('pending_L2', 'Pending Level 2'), ('pending_L3', 'Pending Level 3'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_L1', max_length=20),
        ),
    ]
