# Generated by Django 5.2.1 on 2025-08-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_alter_attendanceadjustment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustmentapproval',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='adjustmentapproval',
            name='created_at',
        ),
    ]
