# Generated by Django 5.2.1 on 2025-08-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0007_remove_adjustmentapproval_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentapproval',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
