# Generated by Django 5.2.1 on 2025-08-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0008_adjustmentapproval_comments'),
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_by', models.DurationField(blank=True, null=True)),
                ('early_out_by', models.DurationField(blank=True, null=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='attendence.attendance')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_semployee', to='employee.employee')),
            ],
            options={
                'ordering': ['-attendance__attendance_date'],
                'unique_together': {('employee', 'attendance')},
            },
        ),
    ]
