# Generated by Django 5.2.1 on 2025-08-06 05:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0009_attendancesummary'),
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('shifting_in_start', models.TimeField(blank=True, default=datetime.time(8, 0), null=True)),
                ('shifting_in_end', models.TimeField(blank=True, default=datetime.time(11, 0), null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('shifting_out_start', models.TimeField(blank=True, default=datetime.time(16, 0), null=True)),
                ('shifting_out_end', models.TimeField(blank=True, default=datetime.time(20, 0), null=True)),
                ('consideration_time', models.DurationField(blank=True, default=datetime.timedelta(seconds=1200), help_text='Time considered for attendance calculation', null=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_in_outs', to='attendence.attendance')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_in_outs', to='employee.employee')),
            ],
            options={
                'ordering': ['-attendance__attendance_date'],
                'unique_together': {('employee', 'attendance')},
            },
        ),
    ]
